sonar.projectKey=askany
sonar.projectName=AskAny - Student Help Forum
sonar.projectVersion=1.0
sonar.sources=src
sonar.tests=tests
sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.exclusions=node_modules/**,coverage/**
sonar.qualitygate.wait=true
